services:
  database:
    image: postgres
    container_name: petsitter_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: petsitter
    ports:
      - "5432:5432"
    volumes:
      - ./petsitter-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petsitter_backend
    volumes:
      - .:/app
      - air_tmp:/tmp
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "petsitter"

volumes:
  air_tmp:
