services:
  database:
    image: bitnami/postgresql:latest
    container_name: petsitter_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: petsitter
    ports:
      - "5432:5432"
    volumes:
      - ./petsitter-data:/var/lib/postgresql/data
    networks:
      - petsitter-network

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "petsitter"
    networks:
      - petsitter-network
  
  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "thales.soul96@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "*Teuc#pgadmin992269956*"
    ports:
      - "5050:80"
    networks:
      - petsitter-network

networks:
  petsitter-network:
    external: true
